version: '3.8'

services:
  db:
    image: postgres:14
    container_name: db
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: db_flashcards
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: adonis-app
    depends_on:
      - db
    ports:
      - "10000:10000"
    environment:
      TZ: UTC
      HOST: 0.0.0.0
      PORT: 10000
      NODE_ENV: production
      APP_KEY: 1emDYkK9Xzrj1eWyXFUiytAXl8Wvdfv4
      DB_CONNECTION: pg
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: root
      DB_PASSWORD: root
      DB_DATABASE: db_flashcards
    networks:
      - app-network
    command: >
      sh -c "
        echo 'Waiting for PostgreSQL...'
        until nc -z db 5432; do
          sleep 1
        done
        echo 'PostgreSQL is ready!'
        node ace migration:run --force
        node ace db:seed --force || echo 'Seeds may have failed, but continuing...'
        node bin/server.js
      "

networks:
  app-network:

volumes:
  pgdata: