version: '3.8'

services:
  db:
    image: mysql:8.0.30
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_flashcards
    ports:
      - "6033:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin:5.2.0
    container_name: pma
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - 8081:80
    networks:
      - app-network

  app:
    build: .
    container_name: adonis-app
    depends_on:
      - db
    ports:
      - "3333:3333"
    environment:
      TZ: UTC
      HOST: 0.0.0.0
      PORT: 3333
      NODE_ENV: development
      APP_KEY: 1emDYkK9Xzrj1eWyXFUiytAXl8Wvdfv4
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_DATABASE: db_flashcards
    volumes:
      - ./:/app
      - /app/node_modules
    networks:
      - app-network
    command: >
      sh -c "
        echo 'Waiting for MySQL...'
        until nc -z db 3306; do
          sleep 1
        done
        echo 'MySQL is ready!'
        node ace migration:run --force
        node ace db:seed --force || echo 'Seeds may have failed, but continuing...'
        npm run dev
      "

networks:
  app-network:

volumes:
  dbdata: